### PR TITLE
TypeScript support

### PR DESCRIPTION
**Pull request by jurca**
Ported the project to TypeScript, as agreed upon here: https://github.com/m59peacemaker/browser-insular-observer/issues/1

### CODE REVIEW

**Comment by m59peacemaker** [comment]
Great stuff! The only thing I see right now that has to be improved is the single character names for generics. Since I don't use typescript regularly, I haven't decided on a convention yet. At least descriptive names in the form `TName` i.e. `TListener` would be an improvement. I am leaning toward `T_Name` i.e. `T_Listener`, as that is both descriptive and easy on the eyes. Of course, this would also mean putting underscores in interface names for consistency: `I_InterfaceName` i.e. `I_ObserverEntry`. At which point, it annoys me that interfaces and generics are distinct by their names in the form of `X_`, but types like `ObserverCallback` aren't. I welcome your experienced thoughts and debate about this! Thanks.

**Comment by jurca** [comment]
I'm glad you like it :).

Single-character names for generics is a wide-spread convention spanning many languages and many years, whoever, I am willing to change that here, no proble.

That being said, I would argue against using `PREFIX_NAME` notation as it mixes snake_case with PascalCase and looks IMHO quite weird. The `I` prefix used with interfaces is what is expected by tslint in the default settings, but that can be changed - consistency is what actually matters.

Therefore I would like to suggest treating all types and identifiers same, and remove the `I` prefixes from interface names. Would you be OK with that?

**Comment by m59peacemaker** [comment]
I talked it over with a friend that had the same suggestion you did - to remove the `I` prefix.
Single character, non-descriptive names are too hard on my brain and I avoid them as much as possible.  Do whatever you think is best for the generics as long as they aren't single characters i.e. "Listener" or "TListener" or something else. Thanks again!

**Comment by jurca** [comment]
I have updated the code. Do you like the current state of it, or would you like me to do more modifications?

**Comment by m59peacemaker** [comment]
Looks great. Unfortunately, I have just realized I can't use tape-run from my current development setup. I switched over to WSL for my Linux environment and I regret it. It looks like `npm test` requires `npm run compile` first. I aim for being able to do this:

```
git clone the-project
cd the-project
npm install
npm test
```

Shouldn't `compile` be called `transpile` in this case? I would do something like this:

```
test-only: test stuff here
test: npm run transpile && npm run test-only
```

Does that sound good? If `npm test` passes all the tests for you, I'll take your word for it and go ahead and merge and npm publish it. I would make these changes myself, if not for this WSL blunder. If necessary, I can revisit this when I get setup in a proper Linux environment again. Sorry for the trouble! I really appreciate your contribution.

**Comment by m59peacemaker** [comment]
I did just notice one another thing... after `npm run compile`, it spams the root project directory with the generated files. I would output any generated stuff to `./build`. IIRC, I would do `mkdir -p ./build && the-build-stuff` and update the entry file to `build/index.js`

**Comment by jurca** [comment]
Thanks for the feedback! I'm sorry to hear about your WSL issues, and I hope the next version of WSL that claims to have better compatibility will improve your situation.

I've made some modifications:
- the `npm test` command no longer requires the source to be compiled, so it should suit the use-case you described
- the compiled files are now located in the `dist` directory as requested.

I value all the trust you put in me by taking my word for it when it comes to the tests passing, however, I do not advise it, people do err :). If your WSL issues persist, I would recommend spinning up a VM. There is another option, however - using free CI, for example https://travis-ci.org/. All you would have to do is register there and enable CI for this repository, and I would do the rest for your.

I would like to argue against renaming the `compile` task to `transpile`, since we are not transpiling JavaScript to JavaScript, but compiling TypeScript to JavaScript. If, however, you insist on renaming the task, I will change the name.

**Comment by m59peacemaker** [comment]
hah, you are quite right about `compile`. That was a blunder on my part. Great work!!

**Pull request merged**
